[package]
name = "systemfd"
version = "0.3.0"
authors = ["Armin Ronacher <armin.ronacher@active-4.com>"]
description = "A convenient helper for passing sockets into another process.  Best to be combined with listenfd and cargo-watch."
keywords = ["socket", "listenfd", "systemd", "socketactivation", "cargo-watch"]
homepage = "https://github.com/mitsuhiko/systemfd"
readme = "README.md"
license = "MIT/Apache-2.0"

[dependencies]
clap = "2.33.2"
failure = "0.1.8"
failure_derive = "0.1.8"
regex = "1.3.9"
lazy_static = "1.4.0"
console = "0.11.3"
libc = "0.2.74"

[target."cfg(unix)".dependencies]
nix = "0.18.0"

[target."cfg(windows)".dependencies]
socket2 = "0.3.12"
uuid = { version = "0.8.1", features = ["v4"] }
winapi = { version = "0.3.9", features = ["winsock2"] }
